### ISSUE TITLE
slow dependency download causes travis deployment to fail

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/annotation-service#295]
The annotation service includes a dependency on google.golang.org/api which must be downloaded twice with the current configuration (once for testing by travis, once for deployment by AppEngine). The total package size is currently around ~719MB (it seems to grow over time). The annotation service has failed four times during the deployment phase while downloading this package.

The mechanism provided by travis to work around [slow operations travis_wait](https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received) is not available during deployment steps.

A third-party package that solves this problem travis-wait-improved provides a tool with the same effect (prevent timeouts) and usable from deployment steps. https://github.com/cisagov/travis-wait-improved

But it does not work, failing with:

```
Traceback (most recent call last):
  File "/home/travis/.local/bin/travis-wait-improved", line 5, in <module>
    from travis_wait_improved.sherpa import main
  File "/home/travis/.local/lib/python2.7/site-packages/travis_wait_improved/sherpa.py", line 29
SyntaxError: Non-ASCII character '\xe2' in file /home/travis/.local/lib/python2.7/site-packages/travis_wait_improved/sherpa.py on line 29, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
Script failed with status 1
```

**Comment by stephen-soltesz** [comment]
See this attempted PR: https://github.com/m-lab/annotation-service/pull/294
